"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var aranha_1 = require("./aranha");
var aranha1 = new aranha_1.Aranha('Aranhazinha');
var aranha2 = new aranha_1.Aranha('Mariazinha');
console.log("Nossas aranhas possuem as seguintes características:");
console.log("Espécie: " + aranha_1.Aranha.especie);
console.log("Cor: " + aranha_1.Aranha.cor);
console.log("Características: " + aranha_1.Aranha.caracteristicas);
console.log("..........................................\n");
console.log("Aranhas registradas: " + aranha1.nome + " e " + aranha2.nome + "\n");
console.log("..........................................\n");
aranha1.andar();
aranha1.fazerTeia();
aranha2.andar();
aranha2.comer();
